# -*- coding: utf-8 -*-
# -*- mode: ruby -*-
# # vi: set ft=ruby :

Vagrant.require_version ">= 1.6.0"

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'rackspace'

require 'fileutils'

CLOUD_CONFIG_PATH = File.join(File.dirname(__FILE__), "user-data")
CONFIG = File.join(File.dirname(__FILE__), "config.rb")

# Defaults for config options defined in CONFIG
$num_instances       = 1
$vm_name_prefix      = ""

# Default Rackspace image preferences, override in CONFIG
# https://coreos.com/docs/running-coreos/cloud-providers/rackspace/
# https://github.com/mitchellh/vagrant-rackspace#configuration
$rs_api_image_flavor = /2GB Standard Instance/
$rs_api_image_id     = "78a24bc3-2545-433b-8067-a5143c04a3c3"
$rs_api_region       = :ord

# Attempt to apply the deprecated environment variable NUM_INSTANCES to
# $num_instances while allowing config.rb to override it
if ENV["NUM_INSTANCES"].to_i > 0 && ENV["NUM_INSTANCES"]
  $num_instances = ENV["NUM_INSTANCES"].to_i
end

if File.exist?(CONFIG)
  require CONFIG
end

Vagrant.configure("2") do |config|
  # plugin conflict
  if Vagrant.has_plugin?("vagrant-vbguest") then
    config.vbguest.auto_update = false
  end

  # the dummy box is an artifact of how vagrant works: necessary to specify, but a "no-op" of sorts
  config.vm.box = "dummy"
  config.vm.box_url = "https://github.com/mitchellh/vagrant-rackspace/raw/master/dummy.box"

  # Vagrant expects the default SSH user to have passwordless sudo configured,
  # which is the case for the `core` user of CoreOS distributions
  config.ssh.username = "core"
  config.ssh.private_key_path = $my_private_key_path

  (1..$num_instances).each do |i|
    config.vm.define vm_name = ($vm_name_prefix + "core-%02d") % i do |config|
      config.vm.hostname = vm_name

      config.vm.provider :rackspace do |rs, override|
        # See https://github.com/mitchellh/vagrant-rackspace#configuration
        rs.username = $rs_api_user
        rs.api_key  = $rs_api_key
        rs.flavor   = $rs_api_image_flavor
        rs.image    = $rs_api_image_id
        rs.disk_config = "MANUAL"
        rs.config_drive = true
        rs.user_data = CLOUD_CONFIG_PATH
        rs.rackspace_region = $rs_api_region
        # ↓ must correspond to `config.ssh.private_key_path`
        rs.public_key_path = $my_public_key_path
        # ↓ optional: pub key uploaded with Rackspace admin panel, so named; must correspond to `config.ssh.private_key_path`
        # rs.key_name = "coreos-key"
        # ↓ optional
        # rs.metadata = {"key" => "value"}
        # ↓ disable default folder sync
        override.vm.synced_folder ".", "/vagrant", disabled: true
      end

      # ↓ disable nfs sync functionality, as there seems to be a bug (error reported when running `vagrant up`)
      config.nfs.functional = false

      config.vm.synced_folder "../..",
                              "/home/core/vagrant",
                              type: "rsync",
                              rsync__exclude: ".git/",
                              rsync__auto: true
      config.vm.provision :shell, :inline => "chown -R core:core /home/core/vagrant", :privileged => true

      # config.vm.provision :file, :source => "/some/local/path/file", :destination => "/tmp/some.file"
      # config.vm.provision :shell, :inline => "echo hello > /tmp/world.txt", :privileged => true
    end
  end
end
